-- ============================================================================
--  PRODUCTION DECONTAMINATION — "Shop Data" (klkfynokcjunqvbkywfk)
--  Business: 7d1f3a52-9c4e-4b18-8f6a-2e5b0c9a4d31  Gridline Auto Parts & Hardware
--  Written: 2026-08-20        Author: audit pass, reviewed by a human before running
-- ============================================================================
--
--  WHAT HAPPENED
--  -------------
--  2026-08-11 → 2026-08-19: two Android phones were device-tested against the
--  THROWAWAY project (lvaxbbobmounfxskooiw), which carries the SAME business_id
--  as production. On 2026-08-20 the app was repointed at PRODUCTION and a
--  "reset and pull" was pressed.
--
--  PosRepository.resetLocalData() wipes sales, sale lines, payments, stock
--  movements, credit, refunds, mobile-money, notifications, staff requests,
--  items, item attributes and customers. It does NOT wipe cash_sessions,
--  cash_txns (the cash ledger), day_closes, outside_funds or staff. So the
--  week of throwaway CASH data survived the reset with its pendingSync flags
--  intact, and the next push shipped it into production:
--
--      10:57:35.730  7 cash_sessions   (bulk push, one server stamp)
--      10:57:37.598  19 cash_movements (bulk push, one server stamp)
--      11:00:05.452  1 more cash_session re-pushed from the second phone
--
--  DISCRIMINATOR USED
--  ------------------
--  A contaminated row has a server `updated_at` of 2026-08-20 but a
--  `client_updated_at` from 11–19 August. Separately, Android pushes stamp
--  `client_updated_at` at MILLISECOND precision (3 significant digits) while
--  web/server writes land at MICROSECOND precision — that second test is what
--  cleared the items catalogue and the staff table (see NOT TOUCHED, below).
--
--  MONEY IMPACT BEING REVERSED
--  ---------------------------
--      pay_in    3 rows    $90.00        pay_out  13 rows   $345.00
--      safe_in   2 rows   $279.00        safe_out  1 row     $24.00
--      => TILL  -$255.00 and SAFE +$255.00 of pure test data in the books.
--
--  NOT TOUCHED BY THIS SCRIPT — verified legitimate, do NOT add them:
--    * items (265 rows). 105 written 08-09 + 67 written 08-11 (=172, matching
--      the known 08-12 count) + 92 written 08-19 + 1 on 08-20. All 264 of the
--      pre-08-20 rows have client_updated_at EXACTLY EQUAL to updated_at at
--      microsecond precision — the signature of a web/server write, not an
--      Android push. The 92 are web data entry on 08-19 (08:24 → 15:29).
--      THE CATALOGUE IS CLEAN.
--    * item_attributes (808 rows). 671 key='car' from 08-09 + 137 rich-key
--      rows from 08-19, all server-written. Nothing on 08-20. CLEAN.
--    * notifications (179 rows). Generated by the device AFTER the pull, off
--      the REAL production catalogue: all 178 item refs resolve to existing
--      production items and every body's stock figure matches items.stock_qty
--      exactly. These are legitimate (if noisy) alerts, NOT throwaway data.
--      An optional noise-clearing block is at the bottom, commented out.
--    * staff (6 rows). The 08-20 writes are WEB activity: "Guruve Shop" was
--      inserted 10:30:38 (client_updated_at = updated_at to the microsecond)
--      and Tanya/Ryan/Enzo/Ashley were deactivated 10:32:32→10:32:54. The
--      throwaway still has all of them active=true, so this state did NOT come
--      from the device. It is deliberate production admin work.
--    * items 0a192c55-1808-42b5-a79a-b89ac61e9725 "M8 Pro LED H4 Light 120000"
--      and stock_movements 9910f074-8cb1-4a34-b54b-ca0cffc4ecbf (restock +5,
--      "Opening stock") — created on the app at 12:14 today, after the repoint.
--    * customers 956d6455-e0bc-4901-b1cd-cb4f4ce6a1ff — pushed 12:23 today,
--      after the repoint, so not throwaway data. It is named "Test" with phone
--      078371596 and is probably junk the owner made while trying the app; an
--      optional block to remove it is at the bottom, commented out.
--    * businesses — untouched since 2026-08-09. CLEAN.
--
--  HOW TO RUN
--  ----------
--  Read it, then run it. It opens a transaction and DOES NOT COMMIT: the final
--  COMMIT is left commented out so a human commits deliberately after reading
--  the verification output. Quarantine tables are created first, so every
--  delete is reversible with a plain INSERT ... SELECT (restore recipe at the
--  end of the file).
--
--  NOTE: this schema has NO foreign key constraints at all (checked against
--  pg_constraint contype='f' — zero rows). Children are still deleted before
--  parents below, as required, so the ordering stays correct if FKs are ever
--  added.
--
--  ⚠ THIS SCRIPT WILL NOT REMOVE THE "CLOSED DAY BY ASHLEY ON 1 JANUARY".
--    That date exists nowhere in this database (see the report). It is rendered
--    on the DEVICE from a local row. Cleaning the cloud will not clear it; the
--    phone's local data has to be cleared. See §6 of the report.
-- ============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- STEP 0 — Safety rail. If these counts are not 19 and 7, the database has
-- moved since the audit (the device may have pushed again). STOP and re-audit
-- rather than running the rest.
-- ---------------------------------------------------------------------------
SELECT
    (SELECT count(*) FROM cash_movements) AS cash_movements_expect_19,
    (SELECT count(*) FROM cash_sessions)  AS cash_sessions_expect_7;

-- ---------------------------------------------------------------------------
-- STEP 1 — BACK UP. Full row copies into timestamped quarantine tables.
-- These are plain tables, not temp tables: they must survive the session so a
-- restore is possible tomorrow, not just in this connection.
-- ---------------------------------------------------------------------------

-- 1a. All 19 cash_movements. Every one is throwaway data: created 08-11→08-19,
--     each client_updated_at 2-3 seconds after its created_at (a live device
--     write), all sharing the single server stamp 2026-08-20 10:57:37.598243.
--     All 19 ids were found in the THROWAWAY project with identical amounts,
--     reasons and timestamps — conclusive proof of origin.
CREATE TABLE _quarantine_cash_movements_20260820 AS
SELECT * FROM cash_movements
WHERE id IN (
    'bc7b1802-27a3-4430-9599-31645d551a47',  -- 08-11 14:36  pay_out   $5.00    Change paid out              (Owner)
    'cf047258-3a74-4612-b741-3f119e701c4e',  -- 08-17 16:49  pay_out   $61.00   Day close — takings to safe  (Ryan)
    '942e4455-50b4-4e03-9bfa-61a64821d055',  -- 08-17 16:49  safe_in   $61.00   Day close — takings to safe  (Ryan)
    'c48409f8-660e-478e-862c-13c4b310d136',  -- 08-17 17:31  pay_out   $10.00   Owner drawing                (Owner)
    '842a2204-57a5-4dd2-912c-a7e162582f92',  -- 08-17 17:32  pay_out   $10.00   Owner drawing                (Owner)
    'cae4d666-5fcd-401e-a166-6c73a31ee9cc',  -- 08-18 17:40  pay_out   $10.00   Owner drawing                (Owner)
    '1e860740-0749-48a5-bc6f-935c9ebc85fc',  -- 08-18 17:43  pay_out   $5.00    Utilities · expense          (Owner)
    'a6104df3-daf3-4089-90b9-dd14c61ca5dd',  -- 08-18 17:45  safe_out  $24.00   Float top-up                 (Owner)
    'e64c2388-8500-4854-9fce-c088ce0c6e8f',  -- 08-18 17:45  pay_in    $24.00   Float top-up                 (Owner)
    '0389b03a-8283-4408-af9c-d6b2f95a29cd',  -- 08-18 17:53  pay_out   $2.00    Change paid out              (Owner)
    '3038da28-e3b3-4b71-8792-2a5deabbf600',  -- 08-19 17:11  pay_in    $60.00   Debt repayment               (Owner)
    'd964cddb-80c0-4737-a053-b43de6f3c41b',  -- 08-19 17:11  pay_in    $6.00    Debt repayment               (Owner)
    'bf3784c2-5c13-4984-8112-a556d94859b3',  -- 08-19 17:12  pay_out   $4.00    Change paid out              (Owner)
    '4a53554b-f6de-45e5-854b-439bf4149512',  -- 08-19 17:12  pay_out   $2.00    Change paid out              (Owner)
    '51748a48-2626-48b7-ba93-6b5905c2fd80',  -- 08-19 17:13  pay_out   $218.00  Day close — takings to safe  (ASHLEY)
    'a87d34bc-ae54-4b04-94a4-fd672e690757',  -- 08-19 17:13  safe_in   $218.00  Day close — takings to safe  (ASHLEY)
    'f0573eb6-b22a-46f9-a9ef-0ebf1dd3f2c3',  -- 08-19 18:24  pay_out   $7.00    Transport · expense          (Owner)
    'f92051ee-b8d0-4c57-aa7c-44aa3a295a71',  -- 08-19 18:26  pay_out   $1.00    Fuel · expense               (Owner)
    '4280e10b-cf81-490b-a9db-8588dff51f98'   -- 08-19 18:27  pay_out   $10.00   Advertising · expense        (Owner)
);

-- 1b. All 7 cash_sessions. Six were matched id-for-id in the THROWAWAY project
--     with identical opened_at/closed_at/counts. The seventh (7b4877b1, till
--     "R8") is NOT in the throwaway — it came off the SECOND test phone's local
--     database, which never pushed it there. It is still test data: it was
--     opened 2026-08-11 05:28 inside the test window, carries the test float of
--     $100.00, and its till code "R8" appears nowhere in production. Flagged
--     below as UNCONFIRMED-BY-CROSSCHECK so a human can make the final call.
CREATE TABLE _quarantine_cash_sessions_20260820 AS
SELECT * FROM cash_sessions
WHERE id IN (
    -- ✔ confirmed present in the throwaway project with matching content
    'dd917f61-b52c-4137-b0d6-96d0b46da8e4',  -- opened 08-11 10:38, till "WG", float $100, auto-closed
    '1918555b-e196-4244-b6ce-14653788b07e',  -- opened 08-11 22:00, "Trading day reconstructed from its sales"
    '29f33606-c159-4abb-ad5b-6381cfce83dc',  -- opened 08-16 22:00, auto-closed 08-17
    'd8f198b3-67e1-4028-ac7a-9fe1e06f78f4',  -- opened 08-17 22:00, auto-closed 08-18
    '64efc858-571a-4a6d-a072-e60998680364',  -- opened 08-18 22:00, auto-closed 08-19; holds all 9 of the 08-19 movements
    'ec860673-ee0a-4ecf-844b-1df94310eccf',  -- opened 08-18 22:00, CLOSED BY ASHLEY 08-19 17:13:
                                             --   counted $318.00, expected $318.00, $218.00 to safe, $100 float.
                                             --   THIS is the "closed day by Ashley" row. Its date is 19 Aug, not 1 Jan.
    -- ⚠ UNCONFIRMED BY CROSS-CHECK — not in the throwaway; judged test data on content
    '7b4877b1-296f-49cd-a7ed-b84ec5bd417b'   -- opened 08-11 05:28, till "R8", float $100, auto-closed;
                                             --   pushed separately at 11:00:05 from the second phone
);

-- ---------------------------------------------------------------------------
-- 1c. The four deactivated staff the owner asked to remove (2026-08-20 instruction:
--     "remove all cashiers other than the admin and Guruve cashiers").
--
--     These are NOT contamination — they are real roster rows from 2026-08-09, and the
--     web deactivated them earlier today (server writes at 10:32:32 → 10:32:54, with
--     client_updated_at untouched at 08-09). They are being removed because the owner
--     wants the roster cut down, not because the repoint touched them.
--
--     Safe to delete in the cloud: `staff` is PULL-ONLY on Android (it is absent from
--     the pushTable list in PosSyncEngine), so no device will re-upload them. Their
--     pin_hash goes with them, so re-adding a person means re-issuing a PIN.
--
--     KEPT: cac27418 Admin (role admin) and 95bc8adc "Guruve Shop" (cashier, created
--     on the web today at 10:30:38).
CREATE TABLE _quarantine_staff_20260820 AS
SELECT * FROM staff
WHERE id IN (
    '766aa4f8-753e-49a6-8240-5924eccf6ea0',  -- Tanya   · cashier · deactivated 10:32:32
    '06ea828b-1654-4ade-b1f3-4ac82b5ee495',  -- Ryan    · cashier · deactivated 10:32:37
    '057b23c0-c36a-4cc5-bca7-985667e8a93b',  -- Enzo    · manager · deactivated 10:32:46
    '49b347ef-2b49-43f9-bf6e-5cc47b019073'   -- Ashley  · manager · deactivated 10:32:54
);

-- STEP 2 — VERIFY THE BACKUP TOOK. 19 and 7. If not, the transaction must be
-- rolled back rather than carried forward into the deletes.
-- ---------------------------------------------------------------------------
SELECT
    (SELECT count(*) FROM _quarantine_cash_movements_20260820) AS backed_up_movements_expect_19,
    (SELECT count(*) FROM _quarantine_cash_sessions_20260820)  AS backed_up_sessions_expect_7;

-- ---------------------------------------------------------------------------
-- STEP 3 — DELETE. Children (cash_movements, which carry session_id) before
-- parents (cash_sessions). Explicit id lists only — never a date predicate,
-- because 2026-08-20 is also the day the LEGITIMATE item, stock movement and
-- customer rows were written, and a date sweep would take them too.
-- ---------------------------------------------------------------------------

-- 3a. CHILD: the 19 throwaway cash ledger rows. Removing these is what takes
--     the fabricated -$255.00 out of the till and +$255.00 out of the safe.
DELETE FROM cash_movements
WHERE id IN (
    'bc7b1802-27a3-4430-9599-31645d551a47', 'cf047258-3a74-4612-b741-3f119e701c4e',
    '942e4455-50b4-4e03-9bfa-61a64821d055', 'c48409f8-660e-478e-862c-13c4b310d136',
    '842a2204-57a5-4dd2-912c-a7e162582f92', 'cae4d666-5fcd-401e-a166-6c73a31ee9cc',
    '1e860740-0749-48a5-bc6f-935c9ebc85fc', 'a6104df3-daf3-4089-90b9-dd14c61ca5dd',
    'e64c2388-8500-4854-9fce-c088ce0c6e8f', '0389b03a-8283-4408-af9c-d6b2f95a29cd',
    '3038da28-e3b3-4b71-8792-2a5deabbf600', 'd964cddb-80c0-4737-a053-b43de6f3c41b',
    'bf3784c2-5c13-4984-8112-a556d94859b3', '4a53554b-f6de-45e5-854b-439bf4149512',
    '51748a48-2626-48b7-ba93-6b5905c2fd80', 'a87d34bc-ae54-4b04-94a4-fd672e690757',
    'f0573eb6-b22a-46f9-a9ef-0ebf1dd3f2c3', 'f92051ee-b8d0-4c57-aa7c-44aa3a295a71',
    '4280e10b-cf81-490b-a9db-8588dff51f98'
);

-- 3b. PARENT: the 7 throwaway trading days, including Ashley's counted day.
--     Removing these clears the fake close history and the $318 count.
DELETE FROM cash_sessions
WHERE id IN (
    'dd917f61-b52c-4137-b0d6-96d0b46da8e4', '1918555b-e196-4244-b6ce-14653788b07e',
    '29f33606-c159-4abb-ad5b-6381cfce83dc', 'd8f198b3-67e1-4028-ac7a-9fe1e06f78f4',
    '64efc858-571a-4a6d-a072-e60998680364', 'ec860673-ee0a-4ecf-844b-1df94310eccf',
    '7b4877b1-296f-49cd-a7ed-b84ec5bd417b'
);

-- ---------------------------------------------------------------------------
-- 3c. The four deactivated staff (see 1c). Independent of the contamination —
--     this is the owner's roster instruction, not a repair. Admin and Guruve Shop
--     are deliberately absent from this list.
DELETE FROM staff
WHERE id IN (
    '766aa4f8-753e-49a6-8240-5924eccf6ea0',  -- Tanya
    '06ea828b-1654-4ade-b1f3-4ac82b5ee495',  -- Ryan
    '057b23c0-c36a-4cc5-bca7-985667e8a93b',  -- Enzo
    '49b347ef-2b49-43f9-bf6e-5cc47b019073'   -- Ashley
);

-- ---------------------------------------------------------------------------
-- STEP 4 — VERIFICATION. Expected after cleanup:
--     cash_movements 0, cash_sessions 0, till_net 0.00, safe_net 0.00,
--     items 265, item_attributes 808, notifications 179, staff 2 (Admin + Guruve Shop),
--     customers 1, stock_movements 1, businesses 1
--   and the three preserved rows each reporting PRESERVED.
-- ---------------------------------------------------------------------------
SELECT 'cash_movements'  AS tbl, count(*) AS n, '0 expected'   AS expect FROM cash_movements
UNION ALL SELECT 'cash_sessions',   count(*), '0 expected'     FROM cash_sessions
UNION ALL SELECT 'items',           count(*), '265 preserved'  FROM items
UNION ALL SELECT 'item_attributes', count(*), '808 preserved'  FROM item_attributes
UNION ALL SELECT 'notifications',   count(*), '179 preserved'  FROM notifications
UNION ALL SELECT 'staff',           count(*), '2 expected'     FROM staff
UNION ALL SELECT 'customers',       count(*), '1 preserved'    FROM customers
UNION ALL SELECT 'stock_movements', count(*), '1 preserved'    FROM stock_movements
UNION ALL SELECT 'businesses',      count(*), '1 preserved'    FROM businesses;

-- The money must be back to zero on both sides.
SELECT
    coalesce(sum(amount) FILTER (WHERE type = 'pay_in'),   0)
  - coalesce(sum(amount) FILTER (WHERE type = 'pay_out'),  0) AS till_net_expect_0,
    coalesce(sum(amount) FILTER (WHERE type = 'safe_in'),  0)
  - coalesce(sum(amount) FILTER (WHERE type = 'safe_out'), 0) AS safe_net_expect_0
FROM cash_movements;

-- The three rows that had to survive the same-day cleanup.
SELECT 'item 0a192c55 M8 Pro LED H4' AS row_checked,
       CASE WHEN EXISTS (SELECT 1 FROM items
                         WHERE id = '0a192c55-1808-42b5-a79a-b89ac61e9725')
            THEN 'PRESERVED' ELSE '*** MISSING ***' END AS state
UNION ALL
SELECT 'stock_movement 9910f074 restock +5',
       CASE WHEN EXISTS (SELECT 1 FROM stock_movements
                         WHERE id = '9910f074-8cb1-4a34-b54b-ca0cffc4ecbf')
            THEN 'PRESERVED' ELSE '*** MISSING ***' END
UNION ALL
SELECT 'customer 956d6455 "Test"',
       CASE WHEN EXISTS (SELECT 1 FROM customers
                         WHERE id = '956d6455-e0bc-4901-b1cd-cb4f4ce6a1ff')
            THEN 'PRESERVED' ELSE '*** MISSING ***' END;

-- ---------------------------------------------------------------------------
--  READ THE OUTPUT ABOVE, THEN COMMIT DELIBERATELY.
--  Leave this commented out unless every number matched.
--  If anything looks wrong, run ROLLBACK; instead — the quarantine tables are
--  created inside this transaction and will disappear with it, which is fine
--  because nothing was deleted either.
-- ---------------------------------------------------------------------------

-- COMMIT;

-- ROLLBACK;   -- <= use this one if the verification did not match


-- ============================================================================
--  RESTORE RECIPE (only after a COMMIT, if the cleanup turns out to be wrong)
-- ============================================================================
--  INSERT INTO cash_sessions  SELECT * FROM _quarantine_cash_sessions_20260820;
--  INSERT INTO cash_movements SELECT * FROM _quarantine_cash_movements_20260820;
--
--  Parents before children on the way back in — the mirror of the delete order.
--  Once the shop is happy, the quarantine tables can be dropped:
--    DROP TABLE _quarantine_cash_movements_20260820;
--    DROP TABLE _quarantine_cash_sessions_20260820;
-- ============================================================================


-- ============================================================================
--  OPTIONAL BLOCK A — clear the low-stock alert noise.
--  NOT contamination: all 178 item references resolve in production and every
--  body matches items.stock_qty. But 177 of them fired in one sweep at 10:28
--  against items whose reorder_level is 0, i.e. the known false-low-stock
--  behaviour, and they are re-pushed on every sync (last seen 14:05:28 today).
--  Only run this if the owner wants the bell cleared. Back up first.
-- ============================================================================
-- CREATE TABLE _quarantine_notifications_20260820 AS
-- SELECT * FROM notifications WHERE category = 'inventory' AND severity = 'warn';
-- DELETE FROM notifications WHERE id IN (SELECT id FROM _quarantine_notifications_20260820);
--   NOTE: the device will simply re-create these on its next alert sweep unless
--   the reorder-level/threshold behaviour is fixed on the app side first.

-- ============================================================================
--  OPTIONAL BLOCK B — remove the "Test" customer.
--  This row is NOT contamination (pushed 12:23 today, after the repoint) but it
--  is named "Test" and looks like scratch data. Owner's call.
-- ============================================================================
-- CREATE TABLE _quarantine_customers_20260820 AS
-- SELECT * FROM customers WHERE id = '956d6455-e0bc-4901-b1cd-cb4f4ce6a1ff';
-- DELETE FROM customers WHERE id = '956d6455-e0bc-4901-b1cd-cb4f4ce6a1ff';
