package com.portionspot.pos.auth

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The till and the web must compute the SAME PIN hash, byte for byte.
 *
 * `staff.pin_hash` is one column in one shared table. A cashier the owner creates in the
 * web back-office has to be able to unlock the phone, and one created on the phone has to
 * work in the browser. If the two derivations differ by a single parameter — the iteration
 * count, the digest, the derived length, the salt seed, the hex casing — nothing errors
 * anywhere. The PIN is simply refused on the other client, forever, and it looks exactly
 * like the cashier typing it wrong.
 *
 * These vectors are not hand-written. They were generated by running the web's own
 * `src/lib/pin.js` algorithm under WebCrypto — the same primitive the browser executes —
 * against this shop's real business id. If a future change to [StaffPin] drifts from the
 * web, this file fails and says so.
 *
 *   KDF             PBKDF2-HMAC-SHA256
 *   iterations      210,000
 *   derived length  256 bits, lowercase hex
 *   salt            SHA-256("PortionSpot POS pin v1:" + businessId)
 *   stored format   pbkdf2$<iterations>$<64 hex>
 */
class StaffPinCompatTest {

    /** Gridline Auto Parts & Hardware — the CLOUD business id, which is the one that
     *  matters: see [saltMustUseTheShopIdTheWebUsed]. */
    private val shop = "7d1f3a52-9c4e-4b18-8f6a-2e5b0c9a4d31"

    private val pin1234 =
        "pbkdf2\$210000\$7fcbe223011a1e3785d3bb16ff2a43af9a99e7e5697332a3675788405be020dd"
    private val pin3333 =
        "pbkdf2\$210000\$c3fc44abac6fc2303dbc4ef0020db9a37441abf6f2259073051ffcb8b2eedb76"
    private val pin1234OtherShop =
        "pbkdf2\$210000\$99c5e14d3d3618cc3904cc7075ffaa9bf8f6b28d70c871c724f871d3071765c8"

    @Test
    fun hashMatchesTheWebByteForByte() {
        assertEquals(pin1234, StaffPin.hash("1234", shop))
        assertEquals(pin3333, StaffPin.hash("3333", shop))
    }

    @Test
    fun aWebAuthoredHashVerifiesOnTheTill() {
        // The whole point: the owner adds a cashier in the browser, the phone accepts it.
        assertTrue(StaffPin.matches("1234", pin1234, shop))
        assertFalse(StaffPin.matches("1235", pin1234, shop))
        assertFalse(StaffPin.matches("", pin1234, shop))
        assertFalse(StaffPin.matches("1234", null, shop))
    }

    @Test
    fun saltMustUseTheShopIdTheWebUsed() {
        // The salt is derived from the business id, so the SAME pin in a different shop
        // hashes differently — which is the point (one rainbow table cannot open every
        // shop). It is also the trap: this device carries TWO business ids, the local uuid
        // it invented on first run and the CLOUD one it adopted. Salt with the local one
        // and every hash silently disagrees with the web's.
        assertEquals(pin1234OtherShop, StaffPin.hash("1234", "other-shop"))
        assertFalse(StaffPin.matches("1234", pin1234, "other-shop"))
        assertFalse(StaffPin.matches("1234", pin1234OtherShop, shop))
    }

    @Test
    fun aBlankPinHasNoHash() {
        assertEquals(null, StaffPin.hash("", shop))
        assertEquals(null, StaffPin.hash("   ", shop))
        assertEquals(null, StaffPin.hash(null, shop))
    }

    @Test
    fun surroundingSpaceIsTrimmedTheSameWayBothSides() {
        // `pin.js` does String(pin ?? '').trim() before deriving. A cashier whose keyboard
        // adds a trailing space must not be locked out on one client only.
        assertEquals(pin1234, StaffPin.hash("  1234  ", shop))
        assertTrue(StaffPin.matches(" 1234 ", pin1234, shop))
    }

    @Test
    fun theStoredIterationCountIsWhatIsReplayed() {
        // The parameters travel with the hash so the count can be raised later without
        // stranding existing accounts. A hash written at a lower count must still verify.
        assertTrue(pin1234.startsWith("pbkdf2\$${StaffPin.ITERATIONS}\$"))
        assertFalse(StaffPin.matches("1234", "pbkdf2\$1000\$${pin1234.substringAfterLast('$')}", shop))
    }

    @Test
    fun junkIsRejectedRatherThanCrashing() {
        for (junk in listOf("", "pbkdf2", "pbkdf2\$210000", "pbkdf2\$abc\$ff", "plain1234", "\$\$\$")) {
            assertFalse("must reject ${'"'}$junk${'"'}", StaffPin.matches("1234", junk, shop))
        }
    }
}
